---
vms:
  - name: "aio0.puppetlabs.vm"
    box:  "puppetlabs/centos-6.6-64-nocm"
    roles: [ "mom" ]

  - name: "com0.puppetlabs.vm"
    box:  "puppetlabs/centos-6.6-64-nocm"
    roles: [ "com" ]

  - name: "node.puppetlabs.vm"
    box: "puppetlabs/centos-6.6-64-nocm"
    roles: [ "posix_agent" ]

  - name: "proxy.puppetlabs.vm"
    box: "puppetlabs/centos-6.6-64-nocm"
    roles: [ "posix_agent" ]
